export { default as Navbar } from "./Navbar";
export { default as About } from "./About";
export { default as Hero } from "./Hero";
export { default as Services } from "./Services";
export { default as Reservation } from "./Reservation";
export { default as Testimonial } from "./Testimonial";
export { default as Faq } from "./Faq";
export { default as Footer } from "./Footer";
export { default as LoginForm } from "./Login";
